schemaVersion: 1

mindexGui:
  locked-entry-display:
    mode: FIXED_ITEM
    material: GRAY_DYE
    custom-model-data:

catalog:
  validateOnLoad: true
  categories:
    - id: mining
      name: "광물"
      file: "category/mining.yml"
      reward: "give %player% diamond 1"
    - id: fishing
      name: "낚시"
      file: "category/fishing.yml"
      reward: "give %player% emerald 1"
